# Generated by Django 4.1.7 on 2023-04-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Data de publicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(max_length=200)),
                ('votos', models.IntegerField()),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pesquisa')),
            ],
        ),
    ]
